site_name: DERCAS — Sistema de Gestión de Incidencias
site_description: Documento de Especificaciones, Requerimientos y Criterios de Aceptación del Software

theme:
  name: material
  language: es

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - with-pdf:
      cover_title: DERCAS — Sistema de Gestión de Incidencias
      cover_subtitle: Documento de Especificaciones, Requerimientos y Criterios de Aceptación del Software
      toc_title: Contenido
      output_path: pdf/DERCAS-Especificaciones.pdf


nav:
  - Portada: portada.md
  - Introducción: Introduccion.md
  - Descripción del proyecto: Descripcion.md
  - Alcance: Alcance.md
  - Especificación de Requerimientos: Requerimientos.md
  - Reglas de negocio: ReglasNegocio.md
  - Criterios de aceptación: CriteriosAceptacion.md
  - Casos de uso: CasosUso.md
  - Arquitectura: Arquitectura.md
  - Modelo de datos: ModeloDatos.md
  - herramientas MCP: HerramientasMCP.md
  - Diagrama de sequencia: DiagramaSecuencia.md
  - Diseño de Seguridad: DisenioSeguridad.md
  - Prototipo: Prototipo.md
  - Cronograma: Cronograma.md
  - Referencias: Referencias.md