[project]
name = "seminario-tecnologias-dercas"
version = "0.1.0"
description = ""
authors = [
    {name = "elaferre@miumg.edu.gt"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material (>=9.7.7,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
mkdocs-pdf-export-plugin = "^0.5.10"
mkdocs-with-pdf = "^0.9.3"

